### ISSUE TITLE
Do not use Pstore binaries in rspec: from_xml

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/relaton#10]
I have changed the way that organisation names are stored in iso-bib-item (they are now arrays of strings rather than single strings), but I find that rspec on relaton can't deal with that, because the mocks for bibliography fetches are accessing Pstore binaries of the caches under spec/support—which I can't readily update to the new internal structure. This is not maintainable, since the internal structure of iso-bib-item is likely to change. 

To deal with this, I request that we use from_xml to build the contents of the Pstore dynamically, as we had it before. That way, any updates to iso-bib-item can be transparently migrated forwards without having to update binary files.

So instead of

````
    file = "spec/support/" + args[0].downcase.gsub(/[\/\s-]/, "_")
    file += "_#{args[1]}" if args[1]
    store = PStore.new file
````

I'd like to see

````
    file = "spec/support/" + args[0].downcase.gsub(/[\/\s-]/, "_")
    file += "_#{args[1]}" if args[1]
    file += ".xml"
    bibitem = File.read(file)
    store = PStore.new "tmp.pstore"
    store.transaction do
      store[:version] = VERSION
      store[args[0]] = IsoBibItem.from_xml bibitem
    end
````

with the XML files restored to the support directory.

Open to other suggestions, including a Pstore builder script, but I think this is the most maintainable alternative.

**Comment by andrew2net** [comment]
@opoudjis I don't understand the problem. The mock get `IsoBibliographicItem` form PStore if a file exists. If not then `IsoBibliographicItem` fetched as in production and stored in PStore. If `IsoBibliographicItem` is changed then we should just remove the PStore file and it will be recreated with a new structure.

**Comment by opoudjis** [comment]
OK, that I didn't realise (although I did notice that design pattern elsewhere in your code). I'll confirm tomorrow, and close the ticket; going to bed now. :)

**Comment by opoudjis** [comment]
Yup, sorry about that. Fixed.

**Comment by ronaldtse** [comment]
BTW, I do not think we should ever have binaries in RSpec, and we should not use a binary cache (at this moment), we should favor a file-based cache like this: 

https://github.com/riboseinc/rfc-asciidoc-rfc/tree/master/references/informative
