### ISSUE TITLE
Get the rspec in metanorma-standoc working

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/relaton#14]
The rspec testing currently in place in relaton and its gems is not very comprehensive. The substantive tests of relaton are in fact in metanorma-standoc. They have assumed the previous structure of writing the raw classes to caches, as part of their testing. But they are also revealing a lot of inconsistencies in how IEV in particular is being processed. I have spent two hours trying to fix the 17 errors I'm getting now in metanorma-standoc, and I have ended up back where I've started.

I therefore need you to fix the errors, and in fact incorporate as much of possible of the relaton testing that this gem does back into the relaton gems where it should be. Some of that will be fixing the rspec code, which is trying put mock caches to work from for entries. Some of that will be fixing the behaviour of the gems themselves: the response for code not found is no longer working, for example. None of it should result in any changes to the metanorma-standoc gem, apart from relaton now returning an XML string rather than an isobibitem class.

This is preventing me pushing the updated metanorma-standoc gem, which is mission critical for the metanorma stack; so this does need to be done within the week.

The gem is at https://github.com/riboseinc/metanorma-standoc

These are the errors to be dealt with: 

````
Finished in 33.31 seconds (files took 0.8212 seconds to load)
118 examples, 17 failures

Failed examples:

rspec ./spec/asciidoctor-standoc/cleanup_spec.rb:809 # Asciidoctor::Standoc separates IEV citations by top-level clause
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:47 # Asciidoctor::Standoc does not activate biblio caches if isobib disabled
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:70 # Asciidoctor::Standoc does not activate biblio caches if isobib caching disabled
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:94 # Asciidoctor::Standoc flushes biblio caches
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:142 # Asciidoctor::Standoc activates global cache
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:164 # Asciidoctor::Standoc activates local cache
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:190 # Asciidoctor::Standoc activates only local cache
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:211 # Asciidoctor::Standoc fetches uncached references
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:243 # Asciidoctor::Standoc expires stale undated references
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:272 # Asciidoctor::Standoc does not expire stale dated references
rspec ./spec/asciidoctor-standoc/isobib_cache_spec.rb:300 # Asciidoctor::Standoc prioritises local over global cache values
rspec ./spec/asciidoctor-standoc/refs_spec.rb:67 # Asciidoctor::Standoc fetches simple ISO reference
rspec ./spec/asciidoctor-standoc/refs_spec.rb:156 # Asciidoctor::Standoc processes dated ISO reference and joint ISO/IEC references
rspec ./spec/asciidoctor-standoc/refs_spec.rb:344 # Asciidoctor::Standoc processes RFC reference in Normative References
rspec ./spec/asciidoctor-standoc/validate_spec.rb:75 # Asciidoctor::Standoc Warning if terms mismatches IEV
rspec ./spec/asciidoctor-standoc/validate_spec.rb:97 # Asciidoctor::Standoc No warning if English term matches IEV
rspec ./spec/asciidoctor-standoc/validate_spec.rb:119 # Asciidoctor::Standoc No warning if French term matches IEV
````

**Comment by andrew2net** [comment]
@opoudjis I have to do some tasks right now. Can do it at the end of the week.

**Comment by andrew2net** [comment]
@opoudjis I started working on it.

**Comment by andrew2net** [comment]
@opoudjis we have `relaton` v0.2.5 dependency in `metanorma-standoc`. Shouldn't we move to v0.2.6 before continuing fix test issues?

**Comment by opoudjis** [comment]
Not until it's working. Ronald is doing a demo. In any case, it's ~>, so it will update locally.

**Comment by andrew2net** [comment]
@opoudjis I have an error. Why does metanorma-standoc change year form 2009 to 2011? Do we need the test case in metanorma-standoc?
```
$ rspec ./spec/asciidoctor-standoc/cleanup_spec.rb:809
...
    Failure/Error:
           expect(strip_guid(Asciidoctor.convert(<<~"INPUT", backend: :standoc, header_footer: true))).to be_equivalent_to <<~"OUTPUT"
...
       Diff:
...
       -  <termsource status="identical">
       -  <origin bibitemid="IEC60050-103" type="inline" citeas="IEC 60050-103:2009"><locality type="clause"><referenceFrom>103-01-02</referenceFrom></locality></origin>
       -</termsource>
       -</term>
       +
       +<termsource status="identical">
       +  <origin bibitemid="IEC60050-103" type="inline" citeas="IEC 60050-103:2011"><locality type="clause"><referenceFrom>103-01-02</referenceFrom></locality></origin>
       +</termsource></term>
...
```

**Comment by andrew2net** [comment]
@opoudjis Should document relation with type `instance` be excluded from relations?
```
...
<relation type="updates">
   <bibitem>
       <formattedref>ISO 123:2001</formattedref>
   </bibitem>
</relation>
<relation type="instance">
       <bibitem type="international-standard">
...
```

**Comment by ronaldtse** [comment]
I'm confused... Why should we exclude `instance` from relations? i.e. a standard document (A) can be an instance of another one (B), "A is within B"?

**Comment by andrew2net** [comment]
@ronaldtse we don't have `instance` in document relation types. Also in Nik's tests case expected "ISO 123" be fetched without relation with the type.

**Comment by opoudjis** [comment]
No, that is intentional, iso-bib-item/lib/iso_bib_item/iso_bibliographic_item.rb: `@relations << DocumentRelation.new(type: "instance", identifier: nil, url: nil, bibitem: me)`. It is used to relate the most recent dated instance of a reference back to an undated reference, e.g. ISO 123:2018 is an instance of ISO 123.

If we don't have it in the document relation types, we need to add it. But that code has been there for a while; what test case it is violating?

**Comment by opoudjis** [comment]
.... I see, it's "fetches simple ISO reference". Investigating.

**Comment by opoudjis** [comment]
.... I don't understand how this has been happening to date, but the test is wrong:

> isobib/lib/isobib/iso_bibliography.rb:        ret.to_most_recent_reference unless year || opts[:keep_year]

This means that if there is an undated reference (`unless year`), and ISO 123 is an undated reference, the instance relation to the most recent instance of the document must be added in. The exception `keep_year` is specific to the year manipulations of IEV. So if now the instance relation is being returned, it needs to go in to the test case.

**Comment by opoudjis** [comment]
Oh, I see why the most recent instance relation wasn't being fetched. The test case (if I'm reading the right one) is prefixed with `mock_isobib_get_123`: it's fetching the reference from a mock, not live from ISO. The instance reference was not included in the mock; and it was not critical for it to be included, since fetching whatever is in the mock suffices to prove the test case.

You can update the mock to include the most recent instance relation, I guess.

**Comment by opoudjis** [comment]
Btw, the instance relation is there in the grammar now (it is a somewhat recent addition). The diagram has not been updated; I will update it now.

https://github.com/riboseinc/relaton-models/blob/master/grammars/biblio.rnc

````
docrelation =
  element relation {
    attribute type {
      ( "obsoletes" | "updates" | "updatedBy" | "complements" | "derivedFrom" | "translatedFrom" |
        "adoptedFrom" | "equivalent" | "identical" | "nonequivalent" | "includedIn" | "includes" |
        "instance" | "partOf" ) },
       element bibitem { BibliographicItem },
       locality*
}
````

**Comment by opoudjis** [comment]
@andrew2net Pull metanorma-standoc; I've just converted the Isobibitem fetched from relaton back to XML, to prevent /asciidoctor/standoc/utils.rb:smart_render_xml() from crashing.

**Comment by andrew2net** [comment]
@opoudjis remain last error in `spec/asciidoctor-standoc/macros_spec.rb` which isn't related to isobib, gbbib etc. I don't know how it should work. Can you help me with it?
```
  1) Asciidoctor::Standoc processes the PlantUML macro
     Failure/Error:
           expect(strip_guid(Asciidoctor.convert(<<~"INPUT", backend: :standoc, header_footer: true))).to be_equivalent_to <<~"OUTPUT"
             #{ASCIIDOC_BLANK_HDR}
...
```

**Comment by opoudjis** [comment]
Huh. That's working my side. I think it just depends on installing the plantuml binary. So don't worry about it.

**Comment by andrew2net** [comment]
@opoudjis ok I'll push all changes, but I can't access to push metanorma-standoc

**Comment by opoudjis** [comment]
Could you make a new branch for metanorma-standoc?

**Comment by andrew2net** [comment]
I made, but it also impossible to push it

**Comment by opoudjis** [comment]
... hang on, let me check

**Comment by opoudjis** [comment]
Just gave you write permission; try now?

**Comment by andrew2net** [comment]
pushed to issue_14 branch, also it needs to pull relaton, iso-bib-item, iecbib

**Comment by opoudjis** [comment]
Ok, thank you. It's 11 pm here, so I will work on it tomorrow. Thank you!

**Comment by ronaldtse** [comment]
@andrew2net if you need PlantUML:

1. On Travis: see how it's done here: https://github.com/riboseinc/metanorma-model-gb/blob/master/.travis.yml
2. On macOS: `brew install plantuml`
3. On Linux: Instructions here: https://github.com/riboseinc/plantuml-install

**Comment by opoudjis** [comment]
Just to let you know, @andrew2net: I have confirmed that everything works my side once I merged the branch in (I had to tweak two rspec cases, but they were minor issues). I will now have to test it against all the dependent gems before releasing.
