### ISSUE TITLE
Additional error with text encoding

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton#17]
```
fetching ISO/IEC 27001...
/var/lib/gems/2.5.0/bundler/gems/relaton-6155dcf62b1c/lib/relaton/db.rb:135:in `bib_retval': invalid byte sequence in US-ASCII (ArgumentError)
	from /var/lib/gems/2.5.0/bundler/gems/relaton-6155dcf62b1c/lib/relaton/db.rb:156:in `check_bibliocache'
```

**Comment by opoudjis** [comment]
Crashing for me too.

Andrej you MUST open all files in db_cache.rb in `encoding: utf-8` (or `r:UTF-8`).

**Comment by andrew2net** [comment]
@opoudjis I think it's not enough to open a file in utf-8. We also have to convert content to utf-8. But to do this we should know in what encoding source is. It's not possible to determine the encoding from content. We can only get encoding from HTTP headers.
What reference cause the error?

**Comment by andrew2net** [comment]
Ok, I'll add encoding utf-8 to all files opening.

**Comment by ronaldtse** [comment]
@andrew2net is this fixed? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse I added encoding utf-8, but I didn't have the problem on my computer. So I can't check if the problem has gone. Could you check?

**Comment by ronaldtse** [comment]
Actually I think the error has gone, I've done a couple documents that use ISO/IEC 27001 but did not see this error. Thanks!
