### ISSUE TITLE
Missing Rake requirement in gemspec?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton#18]
```
Using relaton 0.2.6 from https://github.com/riboseinc/relaton (at master@6155dcf)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/home/travis/build/riboseinc/csand-devsecops-whitepaper/vendor/bundle/ruby/2.5.0/gems/sassc-1.12.1/ext
rake
RUBYARCHDIR=/home/travis/build/riboseinc/csand-devsecops-whitepaper/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/sassc-1.12.1
RUBYLIBDIR=/home/travis/build/riboseinc/csand-devsecops-whitepaper/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/sassc-1.12.1
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in
`find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake
(Gem::GemNotFoundException)
from
/home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in
`activate_bin_path'
	from /home/travis/.rvm/gems/ruby-2.5.1@global/bin/rake:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
rake failed, exit code 1
```

**Comment by andrew2net** [comment]
@ronaldtse there is rake in `Gemfile.lock`. Did you try `bundle install`. What does `bundle list rake` show?
```
$ bundle list rake
/Users/andrej/.rvm/gems/ruby-2.4.0/gems/rake-12.3.1
```

**Comment by ronaldtse** [comment]
It is not via bundle of this gem. The error occurs when I call it using `metanorma-csand`.

You can clone the repo to check:
https://github.com/ribose/csand-devsecops-whitepaper/

Run this to see the error:
```
make clean all
```

**Comment by andrew2net** [comment]
I can't access the link https://github.com/ribose/csand-devsecops-whitepaper/

**Comment by ronaldtse** [comment]
The link has been updated, can you try again?

**Comment by andrew2net** [comment]
<img width="828" alt="2018-10-24 11 55 44" src="https://user-images.githubusercontent.com/5623890/47422817-d809ab00-d783-11e8-82cb-06b9b739f880.png">

**Comment by ronaldtse** [comment]
https://github.com/riboseinc/csand-devsecops-whitepaper/

**Comment by andrew2net** [comment]
I didn't get any error

**Comment by ronaldtse** [comment]
@andrew2net apparently it's still happening on Travis: https://travis-ci.com/riboseinc/csand-devsecops-whitepaper/jobs/154072207

Can you please help fix that one? Thanks!

**Comment by ronaldtse** [comment]
Apparently it is a `sassc` dependency. https://github.com/sass/sassc-ruby/issues/60

**Comment by ronaldtse** [comment]
Moved to https://github.com/riboseinc/isodoc/issues/77. Closing this.
