### ISSUE TITLE
Using a single relaton object to represent multiple stages of a project/documeny

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/relaton#19]
We wish to use a single relaton file to represent a project and its multiple stages (and the associated documents). 

This will be used to generate the pages for individual projects and be able to display the history of document versions.

**Comment by opoudjis** [comment]
This will merely represent relation names and guidance for using relaton to indicate versions of a document within the same artefact.

**Comment by opoudjis** [comment]
Done. Please review.

**Comment by ronaldtse** [comment]
The write up is good but can we have an example of this gets realized? Right now it requires too many (mental) steps to understand how it works...

**Comment by opoudjis** [comment]
Addressed in https://github.com/riboseinc/relaton-models/blob/master/README.adoc
