### ISSUE TITLE
rspec failing

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/relaton#20]
The second time the rspec script retrieves files from the cassette, to serialise them, it is returning "not found". I can replicate the error on the command line, but when running it under byebug, the biblio entries retrieve correctly. There is some context around the VCRs which I cannot work out.

````
  1) Relaton::Db list all elements as a serialization
     Failure/Error: expect(docs.xpath("/documents/bibitem").size).to eq 2
     
       expected: 2
            got: 0
     
       (compared using ==)
````

**Comment by andrew2net** [comment]
I found that algolia lib uses a different domain in the second request. Set URL macher to a path only solve the problem.

**Comment by opoudjis** [comment]
Confirmed
