### ISSUE TITLE
Make mocks work on Travis

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/relaton#4]
I wouldn't normally do this, but I need help getting Travis to work. I have copied the algolia and http mocks across from isobib, to do the same job they do in ISObib. Rspec works fine locally. When I upload to github, Travis act as if the mocks are not there, and fails because it cannot find the ISO references.

**Comment by andrew2net** [comment]
@opoudjis Algolia and other Http requests are out of the Relation gem. So we should mock Isobib, Gbbib, and Rfcbib instead of Algolia and Http.
I'll do it.

**Comment by andrew2net** [comment]
@opoudjis I have the last maser Isobib and can't find any register call. And `@registry.processors` in Relation is empty.

**Comment by opoudjis** [comment]
I had trouble finding it too, when @ronaldtse introduced it in my code. It's in lib/isobib.rb:

````
if defined? Relaton
  require_relative 'relaton/processor'
  Relaton::Registry.instance.register(Relaton::Isobib::Processor)
end
````

**Comment by opoudjis** [comment]
I've replaced the mock with an Isobib::Bibliography mock; it works locally, and still doesn't work on Travis. :(

**Comment by opoudjis** [comment]
And:

````
NickNicBPRetina:relaton nickn$ bin/rspec --format doc
[relaton] processor "isobib" registered

Relaton::Db
[relaton] detecting backends:
isobib
rfcbib
gbbib

[50, 59] in /Users/nickn/Documents/Arbeit/upwork/ribose/relaton/lib/relaton/db.rb
   50:       %r{^GB Standard }.match? code and return :gbbib
   51:       %r{^IETF }.match? code and return :rfcbib
   52:       %r{^(ISO|IEC)[ /]|IEV($| )}.match? code and return :isobib
   53: =end
   54: require "byebug"; byebug;
=> 55:       @registry.processors.each do |name, processor|
   56:         processor.prefix.match? code and return name
   57:       end
   58:       allowed = @registry.processors.inject([]) do |m, (k, v)|
   59:         m << v.prefix.inspect
(byebug) p @registry.processors
{:isobib=>#<Relaton::Isobib::Processor:0x00007fb4341ca378 @short=:isobib, @prefix=/^(ISO|IEC)[ \/]|^IEV($| )/>}
{:isobib=>#<Relaton::Isobib::Processor:0x00007fb4341ca378 @short=:isobib, @prefix=/^(ISO|IEC)[ \/]|^IEV($| )/>}
````

**Comment by andrew2net** [comment]
@opoudjis I made PR with IsoBib mock. Looks like the last IsoBib gem not published. There is a message in the log:
```
ISO 19115-1 does not have a recognised prefix:
```
which means a processor not found.
